package jdk.internal.event;


public class SocketWriteEvent extends Event {

    // The order of these fields must be the same as the parameters in
    // commit(..., String, String, int, long)

    public String host;
    public String address;
    public int port;
    public long bytesWritten;

    public static void commit(long start, long duration, String host, String address, int port, long bytes) {
        // Generated by JFR
    }

    public static boolean shouldCommit(long duration) {
        // Generated by JFR
        return false;
    }

    public static boolean enabled() {
        // Generated by JFR
        return false;
    }

    public static long timestamp() {
        // Generated by JFR
        return 0L;
    }
}
